name: Build and Push Docker Image

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag Name'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 # 推荐：更新 checkout action 版本

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3 # 推荐：更新 buildx action 版本

    - name: Login to Docker Hub
      uses: docker/login-action@v3 # 推荐：更新 login action 版本
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Set tag name
      id: tag_name
      run: |
        TAG=""
        if [ "${{ github.event_name }}" = "release" ]; then
          TAG="${GITHUB_REF#refs/tags/}"
        elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          TAG="${{ github.event.inputs.tag }}"
        fi
        echo "tag=$TAG" >> $GITHUB_OUTPUT # 使用 GITHUB_OUTPUT 设置输出

    - name: Build and push Docker image
      uses: docker/build-push-action@v5 # 推荐：更新 build-push action 版本
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          vinlic/deepseek-free-api:${{ steps.tag_name.outputs.tag }}
          vinlic/deepseek-free-api:latest
        # 将 linux/arm/v7 添加到平台列表中
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        # build-args: TARGETPLATFORM=${{ matrix.platform }} # 这行在这里通常不是必需的
